### ISSUE TITLE
Add feature to strip broken/unneeded key signatures

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1006]
## Description

With the recent DoS attacks on keyservers, some applications have started to use stripped keys.
It would be good to have a way to give RNP a key with signatures, ask it to do a sanity check, and strip bad/broken or irrelevant signatures. Maybe I'd only want to keep the signatures made by one my own private keys.

**Comment by wodry** [comment]
A completely stripped(minimal) public key is needed to send it in the header of an [Autocrypt](https://autocrypt.org/level1.html#openpgp-based-key-data) supporting email.

**Comment by ni4** [comment]
@wodry Thanks for clarification. Since global signature stripping is way more complicated I added function `rnp_key_export_autocrypt()`, which now is merged and should do the job. 
CC @kaie 

Not closing this since it is only partially implemented.

**Comment by kaie** [comment]
Thanks.
Does this API allow exporting of the regular BEGIN PGP PUBLIC KEY BLOCK file format?

Note that my motivation isn't just autocrypt.
I'd like to be compatible with email clients that don't support autocrypt, too.
For that reason, I'd like to attach the sender's key in the regular public key format, too.

Because we'd like to encourage the user to always attach their own key in the regular format, and because users might have imported their existing key with many signatures on it, those keys are big and are inappropriate for attaching it always. Therefore I'd like to attach the reduced sender's key by default. And potentially, we'd attach it in both the regular format and the autocrypt format in parallel, for maximum compatibility.

It seems like your suggested simplification might work for that, if it allows me to export the reduced key in the standard public key file format.

**Comment by ni4** [comment]
@kaie Currently it exports key only in binary format, since autocrypt required raw base64-encoding, which should be applied on top. However, you may easily enarmor it using the `rnp_output_to_armor()` function.
Anyway, exported key would be in regular format, however:
 - it would use only a single userid (which may be a benefit, once user do not want to share other e-mails).
 - it would pick only single encrypting subkey (which may be a problem in case user uses signing subkeys/multiple subkeys with different algorithms and preferences/whatever else).

So, to have 100% functionality it would be needed to wait when signature-stripping flags would be added to `rnp_key_export()`.

**Comment by kaie** [comment]
Thanks for the explanation!
I assume the uid must be a full match.

I'll have to try this a bit later. Thunderbird could do a check if the key follows these requirements. If it's a simple key (which is what Thunderbird creates itself), and it isn't an imported key with a more complex structure, then we could automatically make use of this possibility.

Exporting binary and using enarmor works for me. Thanks.
