### ISSUE TITLE
Add tests for weird userids

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1014]
## Description

Add tests which check whether library and CLI correctly works with weird uids:
 - [ ] with non-ASCII utf-8 characters
 - [ ] with special characters (\t, \n, \0x00, '|', '$', '(', etc).
 - [ ] long userid (more then MAX_ID_LENGTH)
 - [ ] zero-size userid

It should cover following use cases:
 - [ ] pass userid via CLI for key generation
 - [ ] pass userid via CLI as key recipient
 - [ ] pass userid via CLI as signer
 - [ ] list key(s)
 - [ ] dump human-readable and JSON packets
 - [ ] other usages which come to a mind

**Comment by rrrooommmaaa** [comment]
Can I take it?

**Comment by ni4** [comment]
@rrrooommmaaa Sure, but please first wait for #1015 to be merged or branch from it.

**Comment by antonsviridenko** [comment]
Concerning Unicode and UTF-8, I think it is important to perform Unicode canonicalization before processing user id input string. Otherwise visually equal strings may compare as non-equal because they have different representation in their byte sequence, especially when they come from different platforms

https://en.wikipedia.org/wiki/Unicode_equivalence

**Comment by ni4** [comment]
@antonsviridenko Unicode canonicalization would require linking another library, causing more compatibility pain. And bringing not much of value as for me. Most users still will use ASCII symbols for the userid.

**Comment by rrrooommmaaa** [comment]
@ni4 GPG --list-keys escapes special characters in its output (note tab(\x09) and newline(\n):
`uid           [ unknown] }{][)^*.+(\x09\n|$@rnp`
Should rnpkeys do the same? Current output is ugly:
```
uid           }{][)^*.+(
|$@rnp
```
Shall I open a new issue for this?

**Comment by ni4** [comment]
@rrrooommmaaa Yeah, it should be good to escape non-printable chars (0x00-0x1F) in user output. It can be done as a separate function like cli_rnp_user_msg(), so we can later on use it in other places.

**Comment by rrrooommmaaa** [comment]
@ni4 @dewyatt Can you comment on proposed solution to add recipient containing special characters: 
As -r (recipient) parameter accepts regex, in order to correctly quote all imaginable characters, we should either:
change mode to std::regex_constants::ECMAScript, so that special characters can be escaped this way: -r [\x7D][\x7B][\x5D][\x5B][\x29][\x5E][\x2A][\x2E][\x2B][\x28][\x09][\x0A][\x7C][\x24]@rnp
or:
add direct string comparison (as in some other functions) in addition to regex_match (before or after unsuccessful match)

**Comment by ni4** [comment]
@rrrooommmaaa I think there is no need to filter those things that precisely. If somebody requires special characters in search, he can always quote them by himself, or make other search request (i.e. specify keyid or fingerprint).

**Comment by rrrooommmaaa** [comment]
@ni4 to be able to quote `-r <userid>` option, we need to change mode to ECMAScript, otherwise, quoting of special characters isn't working. Do you agree to the proposed update?

**Comment by ni4** [comment]
@rrrooommmaaa I agree as soon as it doesn't break compatibility and works the same way with `regex_t`. There were a discussion somewhere in issues about compatibility and why we started to (partially) use `std::regex`.

But don't we have simpler way, like (just assumption, didn't test it) to use `-r "user\0x09with\0x09tab"`?

**Comment by rrrooommmaaa** [comment]
> But don't we have simpler way, like (just assumption, didn't test it) to use `-r "user\x09with\x09tab"`?
This is implemented for output. As for input, escaping is not implemented, but escaping is not a problem, the problem is the regex processor refuses to take special characters as is, so we have to enable ECMAScript to let the regex processor un-escape the characters itself (in the form of `[\x09]`

**Comment by ni4** [comment]
Fixed via #1053
