### ISSUE TITLE
key 6E620C6562D66B3D causes  rnp_import_keys to fail even with RNP_LOAD_SAVE_PERMISSIVE

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1163]
Call rnp_import_keys with key 6E620C6562D66B3D and RNP_LOAD_SAVE_PERMISSIVE, and the function doesn't ignore the key, but returns a failure.

This key doesn't seem to be on keyservers. I don't know from where I got it. I will send it to you by email.

**Comment by ni4** [comment]
This key has a bit strange structure, having two subkeys with the same key material, but with different creation time. Because of this those subkeys have different keyid/fingerprint but the same key grip (which doesn't include creation time into hash calculation).
And since internally all keys are distinguished by grip, this causes some inconsistency.
Need to think what would be the correct way of handling this.
