### ISSUE TITLE
Importing keyfile without primary key (only subkeys) does not work

### ISSUE THREAD

**Issue by ionum** [rnpgp/rnp#1490]
## Description

Importing only secret-subkeys does not work on Thunderbird 89.0b1

## Steps to Reproduce
1. gpg --export-secret-subkey XXXX > sub.gpg
2. Importing sub.gpg 

## Expected Behavior
Can import sub-keys

## Actual Behavior
Password dialog loops

If i export the same key with gpg --export-secret-key XXXX > full.gpg everything works

**Comment by nwalfield** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1703368

**Comment by ni4** [comment]
@nwalfield Thunderbird's issue 1703368 is unrelated to the gpg, as there secret key packets is replaced with public key packet.
Correct issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1654893

@ionum This feature is available in RNP for a while (since September, 2020, AFAIR, see #1217 ), and seems to become available in the Thunderbird soon, please see the discussion in Bugzilla for more details.

**Comment by ni4** [comment]
...closing this, as it is implemented in RNP.

**Comment by nwalfield** [comment]
@ni4: Thanks for clarifying!
