### ISSUE TITLE
CLI: rnp returns zero result for the unknown command.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1548]
## Description

Command like `rnp --something-wrong` returns 0, while should return non-zero result.
`rnpkeys` behaves correctly in this case.

**Comment by antonsviridenko** [comment]
`rnp` always returns zero on `print_usage`, `rnpkeys` returns failure in the same case. Basically unknown arguments are ignored in both applications. However, should we make it a fatal error when some unknown command line argument is passed? Otherwise now command like `rnp --something-wrong --list-packets some_file` returns success, same for `rnpkeys --something-wrong --list-keys`.

**Comment by ribose-jeffreylau** [comment]
As a user, I would expect CLIs in general to reject with failure any unknown arguments.  This makes non-error cases explicit, which I think is almost always a good thing.

**Comment by ni4** [comment]
Definitely we should return non-zero result in such cases.
