### ISSUE TITLE
When `~/.rnp` doesn't exist, `rnpkeys` prints out "wrong pubring path" which is uninformative

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1559]
## Description

Right after installing RNP, the first run of `rnpkeys` give this output which is incredibly uninformative...

```sh
$ rnpkeys --list-keys
wrong pubring path
...
```

## Expected Behavior

More informative message needed, e.g.
"Initializing ~/.rnp/ directory as keystore..."

## Actual Behavior

What behavior did you observe instead?

```sh
$ rnpkeys --list-keys
wrong pubring path
...
```

**Comment by ni4** [comment]
@ronaldtse Since PR #1592 the message is as following:
```
$ rnpkeys --list-keys
warning: keyring at path '/Users/user/.rnp/pubring.gpg' doesn't exist.
warning: keyring at path '/Users/user/.rnp/secring.gpg' doesn't exist.
Key(s) not found.
```

- Is this good enough, or we may add something like: `Keyrings are empty. Use --generate-key command to generate a new keypair, or --import to import existing.`
- Another option would be to check whether there is populated `~/.gnupg/` directory and then add something like `GnuPG home directory found. To import all keys from the GnuPG, run "gpg -a --export | rnpkeys --import-keys -" for public keys and "gpg -a --export-secret-keys | rnpekys --import-keys -"`
