### ISSUE TITLE
Test Fedora

### ISSUE THREAD

**Issue by ribose-jeffreylau** [rnpgp/rnp#1617]
Fedora 35 has been released, and should be tested.

**Comment by andrey-utkin** [comment]
Fedora 36 has been released since, and I guess we want to test on it, too!
Fedora 35 might be still relevant to us.
Even older releases, 28 and 34, may be as well interesting to us as they are the bases for RHEL 8 and 9 respectively.
And we want to test them with both Botan and OpenSSL backends, if it's not too much to ask of Github Actions.

**Comment by andrey-utkin** [comment]
Raised a blocker https://github.com/riboseinc/yum/issues/9 in relation to adding CentOS 9 to CI :)

**Comment by ronaldtse** [comment]
@andrey-utkin I think RNP should probably provide its own yum repository instead of using the riboseinc one. What do you think?

**Comment by andrey-utkin** [comment]
> @andrey-utkin I think RNP should probably provide its own yum repository instead of using the riboseinc one. What do you think?

RNP probably doesn't need to right now.
The importance of this internal package repository is very small. I'd be grateful to be able to lean on the riboseinc repo and not take on maintenance of another RPM repo.

In this case, these `ribose-automake116*` packages play purely instrumental role of build prerequisites for custom-building GnuPG for CI runs. There are ways to avoid relying on an RPM repo - we could write a Dockerfile which builds it from source in place and preserves the container image for reuse.

**Comment by andrey-utkin** [comment]
PR https://github.com/rnpgp/rnp/pull/1870 merged.
Closing this ticket.
CentOS 9 is not enabled in CI though.
