### ISSUE TITLE
C++ testing framework

### ISSUE THREAD

**Issue by dewyatt** [rnpgp/rnp#733]
## Description

At some point, I think we may want to switch to a C++ testing framework.
cmocka generally works but it can cause incompatibilities with C++ standard headers, so you have to be careful with header ordering and such.

Switching would also offer an opportunity to clean up `src/tests` and split things up more.

Some popular ones I know of are:
* [Google Test](https://github.com/google/googletest)
* [Catch2](https://github.com/catchorg/Catch2)
* [Boost.Test](https://www.boost.org/doc/libs/1_68_0/libs/test/doc/html/index.html)

I have not spent the time evaluating and don't currently have an opinion.

**Comment by randombit** [comment]
Generally +1 to this.

One comment, Botan used Catch for a while (based on the release dates, I think it must have been Catch1 that I used). The build times were terrible because Catch is header only and does tricky template metaprogramming so you can say eg `ASSERT(x < y)` instead of `ASSERT_LT(x,y)`. Which is convenient, but was IMO not worth the extra ~30 seconds compile time per test file. The last straw for me was running into some macro that was evaluating its arguments more than once, so `FOO(side_effecting_operation() == z)` caused incorrect results. Which was like, how do you mess that up? Can't remember the details now and one hopes it has been fixed subsequently, but that made me mad enough to rewrite everything in the test suite to remove Catch. It is entirely possible Catch2 resolves these issues.

I haven't used Gtest or Boost.Test enough to have any opinion on them.

Maybe do a bakeoff? Pick some examplar test of moderate complexity, rewrite the test using all three frameworks, and compare them on the basis of the test code being easy to write and read, compile times, ...

One thing cmocka doesn't do that I wish it did: there is no way to just run a single test, or some subset of tests by name. Often I edit the array of tests when I just need to run 1 or 2 tests repeatedly during development. I would be nice to say `./rnp_tests the_one_i_want` and just run that one test. (I'll admit Catch had a rather nice system for doing this.)

**Comment by dewyatt** [comment]
I put together a quick&dirty bakeoff that tests compile times:
```
git clone --recurse-submodules https://github.com/dewyatt/rnp-testing
cd rnp-testing
./time.sh
```

I just wrapped the minimum of macros to make things work.

#### Boost.Test
https://github.com/riboseinc/rnp/commit/0e69c4acd66d5e7bc3dbc9ec1793e0a20e3ab1d3

`real	0m4.399s`

#### Catch2
https://github.com/riboseinc/rnp/commit/ee09bd49634a935d8f4784b2da8de24c41fdc143

`real	0m16.269s`

#### Google Test
https://github.com/riboseinc/rnp/commit/1b2e7b32ba55d51b0459a56a1f0353c1bdd4f4a1

`real	0m3.282s`

#### My Conclusions

##### Compile Times
I would probably exclude Catch2 based on compile times alone (the `test->minor edit->test` feedback loop should be as quick as possible). I looked at their docs on improving performance and didn't have much luck.

##### Test Readability
All seem about equal as far as test readability (mostly because I kept the same macros though).

##### Selective Test Running
As far as the ability to run an individual test (as @randombit mentioned above), they all support this in one way or another (and really we can always wrap them with CTest for this also).

##### Conclusion
Personally, I'm leaning towards Google Test. Boost.Test also seems nice, though maybe not as popular.

**Comment by ronaldtse** [comment]
@dewyatt with these experiments I agree that Google Test is probably good for us. Thoughts @ni4 ?

**Comment by ni4** [comment]
@ronaldtse @dewyatt Google Test looks good for me as well.

**Comment by dewyatt** [comment]
Ok I'm going to start looking at converting a small subset of tests to use Google Test and see how it goes.

Long term I'm hoping I can parallelize the tests (in GitLab CI) at both the container level and process level to speed things up.

**Comment by ni4** [comment]
@dewyatt @ronaldtse Should we close this now?

**Comment by ronaldtse** [comment]
Yup, since @dewyatt has migrated all the tests to Google tests!

**Comment by ronaldtse** [comment]
That said @dewyatt is test parallelization something to consider still?

**Comment by ni4** [comment]
@ronaldtse if I correct tests are run in parallel since #891
