### ISSUE TITLE
Convert pgp_hash_t to use Botan's C++ interface

### ISSUE THREAD

**Issue by dewyatt** [rnpgp/rnp#944]
## Description

The task here is to convert `pgp_hash_t` to use Botan's C++ interface (`Botan::HashFunction`), rather than Botan's FFI/C interface (`botan_hash_init` etc).

The relevant source is in `src/lib/crypto/hash.*`. If you have any issues with the build then reach out to me as we're not evaluating your CMake skills.

This may or may not end up merged, but we'll be interested in seeing whether all tests pass, etc.

**Comment by dewyatt** [comment]
@joke325 Let me know if you are interested in this task!

**Comment by killy631** [comment]
OK, will do

**Comment by dewyatt** [comment]
Oops wrong person!

**Comment by killy631** [comment]
What then I should do?

**Comment by dewyatt** [comment]
> What then I should do?

I think @ni4 offered an issue in https://github.com/rnpgp/rnp/issues/941 :)

**Comment by joke325** [comment]
This task is good, I'm interested in.

**Comment by dewyatt** [comment]
@joke325 Great! Good luck and let me know if you have any questions!

**Comment by joke325** [comment]
@dewyatt, it seems I don't have rights to open a new branch so I've attached proposed changes in this patch file. RNP tests passed.
[hash_cpp_patch.txt](https://github.com/rnpgp/rnp/files/3802232/hash_cpp_patch.txt)

**Comment by dewyatt** [comment]
@joke325 You should be able to fork this repository to your own account, create a branch there, and create a pull request from that. Let me know if you need any help!

**Comment by joke325** [comment]
@dewyatt I've made the changes on my public clone of RNP.

**Comment by dewyatt** [comment]
@joke325 Great, now you should be able to create a Pull Request to merge that change into this repo.

**Comment by joke325** [comment]
@dewyatt GitHub doesn't allow me to create a PR from joke325/rnp/master to the rnpgp/rnp/master repo.

**Comment by ronaldtse** [comment]
@joke325 it's because you didn't make a "fork" of the rnp repo, you cloned and pushed it.

Can you do this:

1. Remove the "rnp" repo in your account

2. Go to https://github.com/rnpgp/rnp and click "Fork" 

<img width="428" alt="Screen Shot 2019-11-04 at 2 18 05 AM" src="https://user-images.githubusercontent.com/11865/68113790-63467200-fea9-11e9-9bd3-25904630b4ad.png">

3. Push your changes of the local repo to https://github.com/joke325/rnp 

4. Go to https://github.com/rnpgp/rnp/pulls and click "New pull request"

<img width="1169" alt="Screen Shot 2019-11-04 at 2 19 24 AM" src="https://user-images.githubusercontent.com/11865/68113861-91c44d00-fea9-11e9-9f22-feb1f6524ea0.png">

5. Then click "compare across forks" and select your own fork.

<img width="1164" alt="Screen Shot 2019-11-04 at 2 18 57 AM" src="https://user-images.githubusercontent.com/11865/68113839-807b4080-fea9-11e9-866a-4431bc8a59f0.png">

6. Press "create".

**Comment by dewyatt** [comment]
Thanks @ronaldtse I missed that!

**Comment by joke325** [comment]
@dewyatt The forking works. Thanks!

**Comment by joke325** [comment]
@dewyatt (1) I’ve modified code in my PR and I’ve requested you for review. (2) Failed some check in CI and Codecov, could you please outline what’s wrong.

**Comment by dewyatt** [comment]
@joke325 I'll be getting back to you later today on this. Don't worry about the CI or CodeCov failures, those are likely not your fault and I'll be fixing them hopefully today.

**Comment by joke325** [comment]
@dewyatt What about the codecov failures in my PR? And is the PR intended to be merged into the master branch?

**Comment by dewyatt** [comment]
@joke325 I'm not worried about the codecov failures, the tiny decrease in coverage stems from the increase in error-handling code (`RNP_LOG` etc, which is good). I do think it may be worth merging into `master`, so I'll request a second approval for that.

**Comment by ni4** [comment]
@dewyatt As I understand this is fixed in #946 and may be closed?
